### ISSUE TITLE
TODO: `DecideWeights()`

### ISSUE THREAD

**Issue by dharmilshah99** [IshaanReni/SOMAS2023#34]
- This function determines how much you want to listen to each agent by assinging a weighting from 0-1. The total sum of weights should be 1. 

- Option 1: We use the sam weights for all agents so we listen to everyone equally. 
- Option 2: We set the weight for an Agent to be equal to its Social Capital.

To understand how the weight is being used, look into the weights of:
```
func (mb *MegaBike) KickOutAgent(weights map[uuid.UUID]float64) []uuid.UUID {
	voteCount := make(map[uuid.UUID]float64)
	// Count votes for each agent
	for _, agent := range mb.agents {
		agentVotes := agent.VoteForKickout() // Assuming this now returns map[uuid.UUID]int
		for agentID, votes := range agentVotes {
			agentWeight := weights[agentID]
			if val, ok := voteCount[agentID]; ok {
				voteCount[agentID] = float64(val) + agentWeight*float64(votes)
			} else {
				voteCount[agentID] = float64(votes) * agentWeight
			}
		}
	}
```
Essentially you provide the weighting on the votes of agents.

**Comment by neagualexa** [comment]
Pushed on branch alex, alongside other task. (depends on Ishaan's feature for GetBikerWithMinSocialCapital)
Went with option 2 which gives each agent a weight equal to their SC
